name: Blog from Issue

on:
  issues:
    types: [opened, edited, labeled]

permissions:
  contents: write
  issues: write

jobs:
  make-post:
    if: contains(github.event.issue.labels.*.name, 'blog-post')
    runs-on: ubuntu-latest
    env:
      TZ: Europe/London
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create post from issue
        id: create_post
        run: python .github/scripts/make-post.py

      - name: Archive old posts (keep 10 newest)
        run: python .github/scripts/archive-posts.py

      - name: Rebuild indexes
        run: python .github/scripts/build-index.py

      - name: Commit, push, and close issue
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          git config user.name "actuallypav"
          git config user.email "61046893+actuallypav@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "automation: create post and rebuild indexes"
            git push
            echo "Changes committed and pushed."
          else
            echo "No changes to commit."
          fi

          #close the issue
          api_url="https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${ISSUE_NUMBER}"
          curl -sS -X PATCH "$api_url" \
            -H "Authorization: Bearer ${GITHUB_TOKEN}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d '{"state":"closed"}'
