name: Blog from Issue

on:
  issues:
    types: [opened, edited, labeled]

permissions:
  contents: write
  issues: read

jobs:
  make-post:
    if: contains(github.event.issue.labels.*.name, 'blog')
    runs-on: ubuntu-latest
    env:
      TZ: Europe/London

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Create post from issue
        id: meta
        run: node scripts/make-post.js

      - name: Build blog + archive indexes
        run: node scripts/build-index.js

      - name: Commit & push
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name  "CI"
            git config user.email "ci@users.noreply.github.com"
            git add blog/*.md blog/index.json old_posts/**/*.json
            git commit -m "post: ${{ steps.meta.outputs.date }} ${{ steps.meta.outputs.title }}"
            git push
          else
            echo "No changes to commit."
          fi

      - name: Comment back on issue
        uses: actions/github-script@v7
        with:
          script: |
            const p = process.env.path || '${{ steps.meta.outputs.path }}';
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `✅ Post created at \`${p}\` and indexes rebuilt.`
            });