name: Blog from Issue
on:
    issues:
        types: [opened, edited, labeled]

permissions:
    contents: write
    issues: read

jobs:
    make-post:
        if: contains(github.eve.issue.labels.*.name, 'blod-post')
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                node-version: 20

            - name: Make post
              env:
                ISSUE_JSON: ${{ toJson(github.event.issue) }}
              run: node .github/scripts/make-post.js

            - name: Archive rollover
              run: node .github/scripts/archive-posts.js

            - name: Build indexes
              run: node .github/scripts/build-index.js

            - name: Commit changes
              run: |
                git config user.name "github-actions[bot]"
                git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                git add blog/*.md blog/index.json old_posts/**/*.md old_posts/**/index.json
                git commit -m "Blog: #${{ github.event.issue.number }} (post, archive, index)" || echo "Nothing to commit"
                git push